"""tabelas iniciais

Revision ID: 9ecfef8d4e47
Revises: 
Create Date: 2026-09-17 03:15:11.705911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ecfef8d4e47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baby',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('birth', sa.String(length=10), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('live_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sleep_start', sa.BigInteger(), nullable=True),
    sa.Column('sleep_by', sa.Integer(), nullable=True),
    sa.Column('feed_start', sa.BigInteger(), nullable=True),
    sa.Column('feed_kind', sa.String(length=12), nullable=True),
    sa.Column('feed_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('kind', sa.String(length=12), nullable=True),
    sa.Column('start', sa.BigInteger(), nullable=False),
    sa.Column('end', sa.BigInteger(), nullable=True),
    sa.Column('ml', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('by_user_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_start'), ['start'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_updated_at'))
        batch_op.drop_index(batch_op.f('ix_events_start'))

    op.drop_table('events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('live_state')
    op.drop_table('baby')
    # ### end Alembic commands ###
